services:
  - type: web
    name: practica-video-downloader
    runtime: docker
    plan: free
    rootDir: practica
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
