FROM python:3.11-alpine

RUN apk add --no-cache ffmpeg gcc musl-dev linux-headers

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

RUN adduser -D appuser && mkdir downloads && chown -R appuser /app
USER appuser

EXPOSE 5000

CMD ["python", "app.py"]
